server:
  port: 8001
spring:
  application:
    name: tianfujiyunClienta
eureka:
  client:
    service-url:
      defaultZone:  http://39.106.13.18:8000/eureka/   #向Eureka服务器8000  进行注册
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test