server:
  port: 8002
spring:
  application:
    name: tianfujiyunClientb
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8000/eureka/  #向Eureka服务器8000  进行注册
#ribbon:
#  MaxAutoRetries: 2 #最大重试次数找到。当Eureka中可以服务，但是服务连接不上将会重试
#  MaxAutoRetriesNextServer: 3 #切换实例的重试次数
#  OkToRetryOnAllOperations: false #对所有的操作请求都进行重试。如果是get则可以，如果是post，put等操作没有实现幂等的情况下是很危险的，所以设置为false
#  ConnectTimeout: 5000  # 请求连接的超时时间
#  ReadTimeout: 6000  # 请求处理的超时时间


#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000
#  该配置是让Hystrix的超时时间改为5秒
#  方法二
#hystrix.command.default.execution.timeout.enabled: false
#  该配置，用于禁用Hystrix的超时时间
#  方法三
#feign.hystrix.enabled: false


















