eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
server:
  port: 9000
spring:
  application:
    name: zipkin-springCloud
management:
  metrics:
    web:
      server:
      auto-time-requests: false


